### ISSUE TITLE
add stuff to make async nicer

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/ember-console#5]
```
app.visit('/')

// set the following globals?
$_ === the fulfilmment value
$? === the object { state: 'pending' | 'fulfilled' | 'rejected', value: ... } 
```

Or maybe do magic to make it nicer? Can we make the repl's context be an async function?

**Comment by jpadilla** [comment]
I used https://github.com/nfcampos/await-outside in a custom repl I recently built, works well.

**Comment by stefanpenner** [comment]
@jpadilla oh that is awesome.

**Comment by jpadilla** [comment]
@stefanpenner I can put together a PR using that and go from there. Interested?

**Comment by stefanpenner** [comment]
good work @jpadilla !!
